cfi_classes = {
    "E": "Equity",
    "D": "Debt Instruments",
    "C": "Collective Investment Vehicles",
    "R": "Entitlement (Rights)",
    "O": "Listed Options",
    "F": "Futures",
    "S": "Swaps",
    "H": "Non-listed and complex listed options",
    "I": "Spots",
    "J": "Forwards",
    "K": "Strategies",
    "L": "Financing",
    "T": "Referential instruments",
    "M": "Misc. / Others",
}


cfi_types = {
    "ES": "Shares",
    "EP": "Preferred shares",
    "EC": "Convertible shares",
    "EF": "Preferred convertible shares",
    "EL": "Limited partnership units",
    "ED": "Depository receipts on equities",
    "EY": "Structured instruments (participation)",
    "ER": "Preference shares",
    "EV": "Preference convertibles shares",
    "EU": "Units",
    "EM": "Others (Misc.)",
    "DB": "Bonds",
    "DC": "Convertible Bonds",
    "DW": "Bonds with warrants attached",
    "DT": "Medium-term notes",
    "DS": "Structured products (with capital protection)",
    "DE": "Structured products (without capital protection)",
    "DG": "Mortgage-backed securities",
    "DA": "Asset backed securities",
    "DN": "Municipal bonds",
    "DD": "Depository receipts on debt instruments",
    "DY": "Money market instruments",
    "DM": "Others (Misc.)",
}
